extends: ["spectral:oas", "spectral:arazzo"]

rules:
  parameter-description:
    description: All parameters should have a description
    message: Parameter is missing a description.
    severity: warn
    given: $.paths.*.*.parameters[*]
    then:
      field: description
      function: truthy

  operation-must-have-examples:
    description: All object types must include at least one example
    message: Type is missing an example in the schema.
    severity: warn
    given: $..content[application/json]
    then:
      field: schema.example
      function: truthy