extends: ["spectral:oas", "spectral:arazzo"]

rules:
  parameter-description:
    description: All parameters should have a description
    message: Parameter is missing a description.
    severity: warn
    given: $.paths.*.*.parameters[*]
    then:
      field: description
      function: truthy

  operation-must-have-examples-requests:
    description: All object types must include at least one example
    message: Request type is missing an example in the schema.
    severity: warn
    given: $.paths.*.*.*.content[application/json]
    then:
      field: schema.example
      function: truthy

  operation-must-have-examples-responses:
    description: All object types must include at least one example
    message: Response type is missing an example in the schema.
    severity: warn
    given: $.paths.*.*.*.*.content[application/json]
    then:
      field: schema.example
      function: truthy
