extends:
  - "spectral:oas"
  - "spectral:arazzo"

aliases:
  requestOrResponseJsonContent:
    - "$..content[application/json]"

documentationUrl: https://www.guanchen.nl/
rules:
  bank-properties-requires-camel-case:
    description: Property names and acronyms must be in camelCase
    message: Property name or acronym is not in camelCase.
    severity: warn
    given: "$..properties.*~"
    then:
      function: pattern
      functionOptions:
        match: ^[a-z][a-z0-9]*(([A-Z]{2}|[A-Z])[a-z0-9]+)*$

  bank-parameter-description-required:
    description: Parameters must have a description
    message: Parameter is missing a description.
    severity: warn
    given: $.paths.*.*.parameters[*]
    then:
      field: description
      function: truthy

  bank-operation-examples-required:
    description: Object types must include at least one example
    message: Type is missing an example in the schema.
    severity: warn
    given: "#requestOrResponseJsonContent"
    then:
      field: schema.example
      function: truthy

  bank-operation-id-requires-pascal-case:
    description: Operation id's must be in PascalCase (upper camel case)
    message: Operation id is not in PascalCase.
    severity: warn
    given: "$..operationId"
    then:
      function: pattern
      functionOptions:
        match: "^[A-Z](([a-z0-9]+[A-Z]?)*)$"

  bank-operation-response-error-required:
    description: Operations must have an error response
    message: Operation is missing an error response.
    severity: warn
    given: $.paths.*.*.responses
    then:
      function: schema
      functionOptions:
        schema:
          anyOf:
            - required: ["400"]
            - required: ["404"]
